### ISSUE TITLE
Why another browser?

### ISSUE THREAD

**Issue by rahilwazir** [kaktus/kaktus#6]
I'm just curious to know, why needed to create another (minimilastic) browser? :blush:

**Comment by azer** [comment]
@rahilwazir Mainly because current popular browsers have very strict APIs not allowing us to innovate. There is a lot of room for innovation in web browsing as it didn't change much for years. For example, tabbing. [I previously built a tabless browser for Linux](http://github.com/azer/delicious-surf) and used it with Xmonad, it was so simple and productive. That experience taught me that it matters for us to have a handy web browser that lets you browse smoothly. After I switched to Mac, I had to use Google Chrome because alternatives are not good enough. 5 years after, I finally quit my job and left US, and have some free time to build what I believe is good for people.

**Comment by rahilwazir** [comment]
@azer Awesome! I really like the idea. I think [servo/servo](https://github.com/servo/servo) is also moving towards the tabless browser experience.
